from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from app.agents.architect_agent import ArchitectAgent
from app.agents.qa_agent import QAAgent
from app.hooks.hooks import run_hooks
from app.services.self_healing import check_backend, recommend_recovery
from app.services.claude_ecosystem_registry import get_claude_ecosystem_capabilities


ARTIFACT_DIR = Path("jarvis_stage3_artifacts/claude_ecosystem")
EVENT_LOG = ARTIFACT_DIR / "ecosystem_events.jsonl"


def _utc_now() -> str:
    return datetime.utcnow().isoformat()


def _write_event(event: Dict[str, Any]) -> None:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    with EVENT_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")


def run_ecosystem_preflight(
    task: Dict[str, Any] | None = None,
    stage: str = "manual_preflight",
) -> Dict[str, Any]:
    """
    Main safe entrypoint for connecting Claude Ecosystem to Jarvis.

    It does:
    1. before hook
    2. backend health snapshot
    3. architecture review
    4. QA checklist
    5. ecosystem registry summary
    6. after hook
    7. event artifact log
    """
    task = task or {}

    before_hook = run_hooks(
        "before_" + stage,
        {
            "task": task,
            "source": "claude_ecosystem_orchestrator",
        },
    )

    health = check_backend()
    recovery = recommend_recovery(health)

    architect_result = ArchitectAgent().run(task)
    qa_result = QAAgent().run(
        {
            "checks": task.get(
                "checks",
                ["compile", "health", "root_endpoint", "night_api", "artifact_log"],
            )
        }
    )

    registry = get_claude_ecosystem_capabilities()

    status = "ok"
    risks: List[str] = []

    if not health.ok:
        status = "needs_recovery"
        risks.append("backend_health_failed")

    if recovery.get("risk") == "medium":
        risks.append("medium_risk_recovery_required")

    after_hook = run_hooks(
        "after_" + stage,
        {
            "status": status,
            "risks": risks,
            "source": "claude_ecosystem_orchestrator",
        },
    )

    result = {
        "schema": "jarvis.claude_ecosystem.integration.v1_2",
        "created_at": _utc_now(),
        "stage": stage,
        "status": status,
        "risks": risks,
        "task": task,
        "backend_health": health.to_dict(),
        "recovery": recovery,
        "architect": {
            "status": architect_result.status,
            "agent": architect_result.agent,
            "message": architect_result.message,
            "data": architect_result.data,
        },
        "qa": {
            "status": qa_result.status,
            "agent": qa_result.agent,
            "message": qa_result.message,
            "data": qa_result.data,
        },
        "registry_schema": registry.get("schema"),
        "capabilities": registry.get("capabilities"),
        "hooks": {
            "before": before_hook,
            "after": after_hook,
        },
        "next_recommended_actions": [
            "Integrate run_ecosystem_preflight() before risky mission execution.",
            "Run QA after every package/patch generated by Night Mode.",
            "Use recovery recommendation before backend restart/patch.",
            "Store all medium-risk changes as artifacts before applying.",
            "Add DesignToCodeAgent after Claude Design access is confirmed.",
        ],
    }

    _write_event(result)
    return result


def run_before_mission(mission_id: str, payload: Dict[str, Any] | None = None) -> Dict[str, Any]:
    return run_ecosystem_preflight(
        {
            "mission_id": mission_id,
            "payload": payload or {},
            "mode": "before_mission",
        },
        stage="mission_preflight",
    )


def run_after_mission(
    mission_id: str,
    payload: Dict[str, Any] | None = None,
    success: bool = True,
) -> Dict[str, Any]:
    result = run_ecosystem_preflight(
        {
            "mission_id": mission_id,
            "payload": payload or {},
            "success": success,
            "mode": "after_mission",
        },
        stage="mission_postflight",
    )

    if not success:
        result["status"] = "mission_failed_review_required"
        result["risks"].append("mission_failed")

    _write_event(result)
    return result


def run_before_night_mode(payload: Dict[str, Any] | None = None) -> Dict[str, Any]:
    return run_ecosystem_preflight(
        {
            "payload": payload or {},
            "mode": "before_night_mode",
            "policy": "package_first_for_medium_risk",
        },
        stage="night_mode_preflight",
    )


def run_after_night_mode(payload: Dict[str, Any] | None = None) -> Dict[str, Any]:
    return run_ecosystem_preflight(
        {
            "payload": payload or {},
            "mode": "after_night_mode",
            "required_checks": [
                "compile",
                "health",
                "artifact_index",
                "diff_summary",
                "rollback_plan",
            ],
        },
        stage="night_mode_postflight",
    )