from __future__ import annotations

import json
import os
import re
import time
import urllib.request
from pathlib import Path

from app.services.identity_core import JARVIS_NAME
from .artifact_contract import normalize_artifacts
from .external_call_guard import ExternalCallGuard
from .models import AgentMetrics, AgentResult, ArtifactRef, SchemaExtensionProposal, TaskSpec
from .self_healing import SelfHealingEngine
from .service_resolver import ServiceResolver
from .service_telemetry import ServiceTelemetryStore
from .service_trace import ServiceTraceStore


class BaseAgentAdapter:
    def invoke(self, agent_id: str, task: TaskSpec, dispatch: dict, context: dict) -> AgentResult:
        raise NotImplementedError


class FallbackTemplateAdapter(BaseAgentAdapter):
    def invoke(self, agent_id: str, task: TaskSpec, dispatch: dict, context: dict) -> AgentResult:
        started = time.time()
        generated_dir = Path(context.get("generated_dir", "state/agent_mesh/demo_artifacts"))
        generated_dir.mkdir(parents=True, exist_ok=True)

        summary = f"{agent_id} completed task '{task.title}'"
        normalized_text = f"Result for task {task.task_id}"
        artifacts = []
        next_actions = []
        handoff_notes = ["mode=fallback_template", "service=fallback"]

        if task.required_capability == "plan":
            normalized_text = "Mission graph prepared with dependency-aware sequencing, consultation checkpoints and QA gating."
            next_actions = ["Dispatch ready tasks", "Open consultation window for risky tasks"]
        elif task.required_capability in {"analyze", "compare", "summarize"}:
            normalized_text = "Relevant context gathered. Reuse prior artifacts where possible and keep cloud as primary provider."
        elif task.required_capability in {"codegen", "patch", "refactor", "debug"}:
            html = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>{task.title}</title></head>
<body><h1>{task.title}</h1><p>Generated by {agent_id}</p></body>
</html>"""
            out = generated_dir / f"{task.task_id}.html"
            out.write_text(html, encoding="utf-8")
            artifacts.append(ArtifactRef(name=out.name, path=str(out), kind="html"))
            normalized_text = html
            next_actions = ["Run QA validation", "Persist artifact reference"]
        elif task.required_capability in {"validate", "smoke_test", "review"}:
            normalized_text = "Validation passed. No blocking issues were detected in the current artifact set."
            next_actions = ["Commit result", "Update mission memory"]
        elif task.required_capability in {"memory_write", "context_bundle", "obsidian_sync"}:
            out = generated_dir / f"{task.task_id}.json"
            out.write_text(json.dumps({"task_id": task.task_id, "summary": "Memory bundle persisted locally."}, ensure_ascii=False, indent=2), encoding="utf-8")
            artifacts.append(ArtifactRef(name=out.name, path=str(out), kind="json"))
            normalized_text = "Memory bundle persisted locally using the local memory layer."
            summary = "Persist memory bundle locally"

        artifacts = normalize_artifacts(
            artifacts=artifacts,
            agent_id=agent_id,
            task_id=task.task_id,
            validation_state="unknown",
        )

        metrics = AgentMetrics(
            duration_ms=int((time.time() - started) * 1000),
            tokens_in=32,
            tokens_out=24,
            cost_estimate=0.0,
        )

        proposals = []
        if task.required_capability == "plan":
            proposals.append(
                SchemaExtensionProposal(
                    field_name="execution_recommendations",
                    field_type="list[str]",
                    reason="Agent wants to provide structured follow-up recommendations.",
                    scope="mission",
                )
            )

        dynamic_fields = {}
        proposed_capability = str(task.metadata.get("proposed_capability") or "").strip()
        if proposed_capability:
            dynamic_fields["proposed_capability"] = proposed_capability

        return AgentResult(
            agent_id=agent_id,
            status="ok",
            summary=summary,
            normalized_text=normalized_text,
            artifacts=artifacts,
            next_actions=next_actions,
            confidence=0.58,
            metrics=metrics,
            error=None,
            proposed_schema_extensions=proposals,
            dynamic_fields=dynamic_fields,
            handoff_notes=handoff_notes,
            validation_hints=["Fallback template was used; verify result before broader promotion."],
            risk_notes=["Fallback template was used; external service path did not complete."],
        )


class LiveLLMAdapter(BaseAgentAdapter):
    def __init__(self, base_dir: str | Path = "state/agent_mesh") -> None:
        self.base_dir = Path(base_dir)
        self.connectors_path = self.base_dir / "connectors.json"
        self.secrets_path = self.base_dir / "secrets_registry.json"
        self.trace = ServiceTraceStore(self.base_dir / "service_trace.jsonl")
        self.telemetry = ServiceTelemetryStore(self.base_dir / "service_telemetry.json")
        self.guard = ExternalCallGuard(self.base_dir)
        self.healing = SelfHealingEngine(self.base_dir)
        self.resolver = ServiceResolver(self.base_dir)
        self.fallback = FallbackTemplateAdapter()

    def _load_json(self, path: Path, default):
        if not path.exists():
            return default
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return default

    def _connectors(self) -> list[dict]:
        return self._load_json(self.connectors_path, {"connectors": []}).get("connectors", [])

    def _secret_refs(self) -> dict:
        return self._load_json(self.secrets_path, {"secrets": {}}).get("secrets", {})

    def _connector_by_service(self, service: str) -> dict | None:
        for item in self._connectors():
            if str(item.get("service") or "").strip().lower() == service:
                return item
        return None

    def _resolve_secret(self, secret_name: str) -> str:
        refs = self._secret_refs()
        item = refs.get(secret_name, {})
        env_var = str(item.get("env_var") or "")
        file_path = str(item.get("file_path") or "")

        if env_var and os.getenv(env_var):
            return os.getenv(env_var, "")
        if file_path and Path(file_path).exists():
            try:
                return Path(file_path).read_text(encoding="utf-8").strip()
            except Exception:
                return ""
        return ""

    def _service_configured(self, service: str) -> bool:
        c = self._connector_by_service(service)
        if not c:
            return False

        auth_type = str(c.get("auth_type") or "").lower()
        metadata = c.get("metadata", {}) or {}
        secret_name = str(metadata.get("secret_name") or "")
        base_url = str(metadata.get("base_url") or "")

        if auth_type == "local_bridge":
            return bool(base_url)
        if auth_type == "webhook":
            if metadata.get("requires_secret", False):
                return bool(base_url and self._resolve_secret(secret_name))
            return bool(base_url)
        return bool(secret_name and self._resolve_secret(secret_name))

    def _post_json(self, url: str, headers: dict[str, str], body: dict, timeout: float) -> dict:
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
        req = urllib.request.Request(url=url, data=data, method="POST")
        req.add_header("Content-Type", "application/json")
        for k, v in headers.items():
            req.add_header(k, v)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8", errors="ignore")
            return json.loads(raw)

    def _extract_json(self, text: str) -> dict:
        text = (text or "").strip()
        if not text:
            return {}
        try:
            return json.loads(text)
        except Exception:
            pass

        fenced = re.findall(r"```json\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
        for item in fenced:
            try:
                return json.loads(item.strip())
            except Exception:
                pass

        match = re.search(r"\{.*\}", text, flags=re.DOTALL)
        if match:
            try:
                return json.loads(match.group(0))
            except Exception:
                pass
        return {}

    def _build_messages(self, agent_id: str, task: TaskSpec, context: dict) -> tuple[str, str]:
        guidance = task.metadata.get("learning_guidance", {}) or {}
        consult_summaries = context.get("consultation_summaries", []) or []
        recommended_actions = guidance.get("recommended_actions", []) or []
        caution_notes = guidance.get("caution_notes", []) or []
        lesson_summaries = guidance.get("lesson_summaries", []) or []
        knowledge_summaries = guidance.get("knowledge_summaries", []) or []

        system = (
            f"You are a structured {JARVIS_NAME} agent. "
            "Return ONLY valid JSON with keys: summary, normalized_text, next_actions, "
            "validation_hints, risk_notes, dynamic_fields, artifact_kind, artifact_name, artifact_content."
        )

        user = f"""
Agent: {agent_id}
Task title: {task.title}
Task type: {task.task_type}
Capability: {task.required_capability}
Priority: {task.priority}
Risk: {task.risk_level}
Dependencies: {task.depends_on}
Preferred service: {task.metadata.get("preferred_service", "")}
Needs memory support: {task.metadata.get("needs_memory_support", False)}
Consult summaries: {consult_summaries}
Recommended actions from learning: {recommended_actions}
Caution notes from learning: {caution_notes}
Relevant past lesson summaries: {lesson_summaries}
Relevant structured knowledge: {knowledge_summaries}

Instructions:
- Return compact, valid JSON only.
- If task is planning: output structured plan.
- If task is research: output concise useful context.
- If task is codegen/debug/refactor: output useful implementation; include artifact fields if relevant.
- If task is validation: output validation-focused result.
"""
        return system, user.strip()

    def _call_openai(self, model: str, system: str, prompt: str, timeout: float) -> str:
        healing = self.healing.load()
        c = self._connector_by_service("openai") or {}
        metadata = c.get("metadata", {}) or {}
        secret_name = str(metadata.get("secret_name") or "openai_api_key")
        api_key = self._resolve_secret(secret_name)

        raw_base = os.getenv("OPENAI_BASE_URL", "https://api.openai.com").rstrip("/")
        endpoint_candidates = []
        if raw_base.endswith("/v1"):
            endpoint_candidates.append(f"{raw_base}/chat/completions")
        else:
            endpoint_candidates.append(f"{raw_base}/v1/chat/completions")
            if bool(healing.get("openai_endpoint_compatibility", True)):
                endpoint_candidates.append(f"{raw_base}/chat/completions")

        model_candidates = []
        for item in [
            model,
            os.getenv("OPENAI_MODEL"),
            os.getenv("LLM_MODEL"),
            "gpt-4o-mini",
            "gpt-4.1-mini",
        ]:
            if item and item not in model_candidates:
                model_candidates.append(item)

        last_error = None
        for endpoint in endpoint_candidates:
            for model_name in model_candidates:
                try:
                    data = self._post_json(
                        endpoint,
                        headers={"Authorization": f"Bearer {api_key}"},
                        body={
                            "model": model_name,
                            "temperature": 0.2,
                            "messages": [
                                {"role": "system", "content": system},
                                {"role": "user", "content": prompt},
                            ],
                        },
                        timeout=timeout,
                    )
                    choices = data.get("choices", []) or []
                    if choices:
                        return str((((choices[0] or {}).get("message") or {}).get("content")) or "").strip()
                except Exception as exc:
                    last_error = exc
                    continue

        raise RuntimeError(f"OpenAI call failed on all candidate endpoints/models: {last_error}")

    def _call_claude(self, model: str, system: str, prompt: str, timeout: float) -> str:
        healing = self.healing.load()
        c = self._connector_by_service("claude_bridge") or {}
        metadata = c.get("metadata", {}) or {}
        secret_name = str(metadata.get("secret_name") or "claude_api_key")
        api_key = self._resolve_secret(secret_name)

        models = []
        for item in [
            model,
            os.getenv("CLAUDE_MODEL"),
            os.getenv("ANTHROPIC_MODEL"),
            "claude-3-7-sonnet-latest",
            "claude-3-5-sonnet-latest",
        ]:
            if item and item not in models:
                models.append(item)

        last_error = None
        for model_name in models:
            try:
                body = {
                    "model": model_name,
                    "max_tokens": 1600,
                    "temperature": 0.2,
                    "system": system,
                    "messages": [{"role": "user", "content": prompt}],
                }
                if bool(healing.get("anthropic_safe_mode", False)):
                    body = {
                        "model": model_name,
                        "max_tokens": 1200,
                        "temperature": 0.2,
                        "messages": [{"role": "user", "content": f"{system}\n\n{prompt}"}],
                    }

                data = self._post_json(
                    "https://api.anthropic.com/v1/messages",
                    headers={
                        "x-api-key": api_key,
                        "anthropic-version": "2023-06-01",
                    },
                    body=body,
                    timeout=timeout,
                )
                content = data.get("content", []) or []
                parts = []
                for item in content:
                    if isinstance(item, dict) and item.get("type") == "text":
                        parts.append(str(item.get("text") or ""))
                joined = "\n".join(parts).strip()
                if joined:
                    return joined
            except Exception as exc:
                last_error = exc
                continue

        raise RuntimeError(f"Claude call failed on all candidate models: {last_error}")

    def _call_ollama(self, model: str, system: str, prompt: str, timeout: float) -> str:
        c = self._connector_by_service("ollama") or {}
        metadata = c.get("metadata", {}) or {}
        base_url = str(metadata.get("base_url") or "http://127.0.0.1:11434").rstrip("/")
        data = self._post_json(
            f"{base_url}/api/generate",
            headers={},
            body={
                "model": model,
                "system": system,
                "prompt": prompt,
                "stream": False,
            },
            timeout=timeout,
        )
        return str(data.get("response") or "").strip()

    def _create_artifacts(self, task: TaskSpec, parsed: dict, generated_dir: Path):
        artifacts = []

        artifact_kind = str(parsed.get("artifact_kind") or "").strip().lower()
        artifact_name = str(parsed.get("artifact_name") or "").strip()
        artifact_content = str(parsed.get("artifact_content") or "").strip()

        if not artifact_content and task.required_capability in {"codegen", "patch", "refactor", "debug"}:
            normalized = str(parsed.get("normalized_text") or "").strip()
            if "<html" in normalized.lower() or normalized.startswith("<!DOCTYPE html"):
                artifact_content = normalized
                artifact_kind = artifact_kind or "html"
                artifact_name = artifact_name or f"{task.task_id}.html"

        if artifact_content:
            if not artifact_kind:
                artifact_kind = "txt"
            if not artifact_name:
                artifact_name = f"{task.task_id}.txt"

            out = generated_dir / artifact_name
            out.write_text(artifact_content, encoding="utf-8")
            artifacts.append(ArtifactRef(name=out.name, path=str(out), kind=artifact_kind))

        return normalize_artifacts(
            artifacts=artifacts,
            agent_id="",
            task_id=task.task_id,
            validation_state="unknown",
        )

    def _build_result_from_parsed(
        self,
        agent_id: str,
        task: TaskSpec,
        service: str,
        parsed: dict,
        generated_dir: Path,
        duration_ms: int,
    ) -> AgentResult:
        summary = str(parsed.get("summary") or f"{agent_id} completed task '{task.title}' via {service}").strip()
        normalized_text = str(parsed.get("normalized_text") or "").strip()

        if task.required_capability in {"memory_write", "context_bundle", "obsidian_sync"} and service == "ollama":
            summary = "Persist memory bundle locally"
            if not normalized_text:
                normalized_text = "Memory bundle persisted using the local Ollama-backed memory layer."

        next_actions = [str(x).strip() for x in list(parsed.get("next_actions", []) or []) if str(x).strip()]
        validation_hints = [str(x).strip() for x in list(parsed.get("validation_hints", []) or []) if str(x).strip()]
        risk_notes = [str(x).strip() for x in list(parsed.get("risk_notes", []) or []) if str(x).strip()]
        dynamic_fields = dict(parsed.get("dynamic_fields", {}) or {})

        proposed_capability = str(task.metadata.get("proposed_capability") or "").strip()
        if proposed_capability and "proposed_capability" not in dynamic_fields:
            dynamic_fields["proposed_capability"] = proposed_capability

        artifacts = self._create_artifacts(task, parsed, generated_dir)
        for art in artifacts:
            try:
                art.metadata["producer_agent"] = agent_id
            except Exception:
                pass

        proposals = []
        if task.required_capability == "plan":
            proposals.append(
                SchemaExtensionProposal(
                    field_name="execution_recommendations",
                    field_type="list[str]",
                    reason="Agent wants to provide structured follow-up recommendations.",
                    scope="mission",
                )
            )

        confidence = 0.84 if service in {"openai", "claude_bridge"} else 0.76 if service == "ollama" else 0.7

        return AgentResult(
            agent_id=agent_id,
            status="ok",
            summary=summary,
            normalized_text=normalized_text,
            artifacts=artifacts,
            next_actions=next_actions,
            confidence=confidence,
            metrics=AgentMetrics(
                duration_ms=duration_ms,
                tokens_in=128,
                tokens_out=192,
                cost_estimate=0.01 if service in {"openai", "claude_bridge"} else 0.0,
            ),
            error=None,
            proposed_schema_extensions=proposals,
            dynamic_fields=dynamic_fields,
            risk_notes=risk_notes or [f"Service used: {service}"],
            handoff_notes=[f"service={service}", "mode=live"],
            validation_hints=validation_hints or ["Verify result before broad autonomous promotion."],
        )

    def invoke(self, agent_id: str, task: TaskSpec, dispatch: dict, context: dict) -> AgentResult:
        started = time.time()
        generated_dir = Path(context.get("generated_dir", "state/agent_mesh/demo_artifacts"))
        generated_dir.mkdir(parents=True, exist_ok=True)

        desired_service = str(task.metadata.get("preferred_service") or "")
        guidance_domains = list(((task.metadata.get("learning_guidance") or {}).get("domain_paths")) or [])
        services = self.resolver.candidate_services(task, agent_id=agent_id)
        errors = []
        attempted = []

        for service in services:
            if service != "ollama" and not self._service_configured(service):
                continue

            if self.guard.is_open(service):
                errors.append(f"{service}: circuit_open")
                continue

            retries = max(1, self.guard.retries(service))
            timeout = max(30, self.guard.timeout_seconds(service))

            for _ in range(retries):
                attempted.append(service)
                try:
                    system, prompt = self._build_messages(agent_id, task, context)
                    raw = ""

                    if service == "claude_bridge":
                        raw = self._call_claude(
                            model=os.getenv("CLAUDE_MODEL") or os.getenv("ANTHROPIC_MODEL") or "claude-3-7-sonnet-latest",
                            system=system,
                            prompt=prompt,
                            timeout=timeout,
                        )
                    elif service == "openai":
                        raw = self._call_openai(
                            model=os.getenv("OPENAI_MODEL") or os.getenv("LLM_MODEL") or "gpt-4o-mini",
                            system=system,
                            prompt=prompt,
                            timeout=timeout,
                        )
                    elif service == "ollama":
                        raw = self._call_ollama(
                            model=os.getenv("OLLAMA_MODEL") or os.getenv("LLM_MODEL") or "llama3.2:latest",
                            system=system,
                            prompt=prompt,
                            timeout=timeout,
                        )
                    else:
                        continue

                    parsed = self._extract_json(raw)
                    if not parsed:
                        parsed = {
                            "summary": f"{agent_id} completed task '{task.title}' via {service}",
                            "normalized_text": raw[:6000],
                            "next_actions": ["Review result", "Persist useful outputs"],
                            "validation_hints": ["Response was not structured JSON; verify carefully."],
                            "risk_notes": [],
                            "dynamic_fields": {},
                        }

                    duration_ms = int((time.time() - started) * 1000)

                    self.guard.record_success(service)
                    self.telemetry.record(
                        service=service,
                        ok=True,
                        latency_ms=duration_ms,
                        dry_run=bool(task.metadata.get("dry_run", False)),
                        mode="live",
                    )
                    self.trace.append(
                        task_id=task.task_id,
                        agent_id=agent_id,
                        capability=task.required_capability,
                        task_type=task.task_type,
                        planned_provider=str(dispatch.get("provider") or ""),
                        desired_service=desired_service,
                        attempted_service=",".join(attempted),
                        actual_service=service,
                        status="success",
                        reason="live_service_selected",
                        dry_run=bool(task.metadata.get("dry_run", False)),
                        guidance_domains=guidance_domains,
                    )

                    return self._build_result_from_parsed(
                        agent_id=agent_id,
                        task=task,
                        service=service,
                        parsed=parsed,
                        generated_dir=generated_dir,
                        duration_ms=duration_ms,
                    )
                except Exception as exc:
                    err = str(exc)[:400]
                    errors.append(f"{service}: {err}")
                    self.guard.record_failure(service, err)
                    self.telemetry.record(
                        service=service,
                        ok=False,
                        latency_ms=int((time.time() - started) * 1000),
                        dry_run=bool(task.metadata.get("dry_run", False)),
                        mode="live",
                    )
                    self.telemetry.set_last_error(service, err)
                    continue

        result = self.fallback.invoke(agent_id, task, dispatch, context)
        result.handoff_notes = [
            "service=fallback",
            "mode=fallback_template",
            f"desired_service={desired_service}",
            f"attempted_services={','.join(attempted)}",
            f"live_error={' | '.join(errors)[:700]}",
        ]
        result.validation_hints = list(result.validation_hints or []) + ["All live services failed; fallback template was used."]
        return result


class AdapterFactory:
    def __init__(self, base_dir: str | Path = "state/agent_mesh") -> None:
        self.live = LiveLLMAdapter(base_dir=base_dir)

    def get(self, agent_id: str, provider: str) -> BaseAgentAdapter:
        return self.live