from __future__ import annotations

import re
from collections import defaultdict

from .artifact_models import ArtifactTaskType
from .mission_artifact_models import (
    MissionArtifactCandidate,
    MissionArtifactPlan,
    MissionArtifactRequest,
)


KEYWORDS: dict[ArtifactTaskType, list[tuple[str, int]]] = {
    ArtifactTaskType.SITE: [
        ("site", 6),
        ("website", 8),
        ("landing", 9),
        ("landing page", 12),
        ("page", 4),
        ("html", 5),
        ("css", 4),
        ("frontend", 5),
        ("web", 4),
        ("лендинг", 12),
        ("сайт", 10),
        ("страница", 6),
    ],
    ArtifactTaskType.TABLE: [
        ("table", 8),
        ("spreadsheet", 10),
        ("sheet", 6),
        ("csv", 9),
        ("report", 5),
        ("calendar", 6),
        ("content calendar", 12),
        ("таблица", 10),
        ("отчёт", 5),
        ("календарь", 6),
    ],
    ArtifactTaskType.GAME: [
        ("game", 10),
        ("mini-game", 12),
        ("clicker", 12),
        ("snake", 10),
        ("browser game", 12),
        ("игра", 10),
        ("мини-игра", 12),
        ("кликер", 12),
    ],
    ArtifactTaskType.YOUTUBE_PACK: [
        ("youtube", 10),
        ("channel", 6),
        ("content pack", 10),
        ("starter pack", 10),
        ("video ideas", 8),
        ("thumbnail", 6),
        ("script", 6),
        ("ютуб", 10),
        ("канал", 6),
        ("сценарий", 6),
        ("превью", 5),
    ],
}


def _normalize_text(value: str) -> str:
    return re.sub(r"\s+", " ", (value or "").strip().lower())


def classify_objective(request: MissionArtifactRequest) -> list[MissionArtifactCandidate]:
    if request.preferred_task_type:
        return [
            MissionArtifactCandidate(
                task_type=request.preferred_task_type,
                score=1000,
                reasons=["preferred_task_type override"],
            )
        ]

    text = _normalize_text(request.objective)
    scores: dict[ArtifactTaskType, int] = defaultdict(int)
    reasons_map: dict[ArtifactTaskType, list[str]] = defaultdict(list)

    for task_type, keyword_entries in KEYWORDS.items():
        for keyword, weight in keyword_entries:
            if keyword in text:
                scores[task_type] += weight
                reasons_map[task_type].append(f"matched '{keyword}' (+{weight})")

    if not scores:
        scores[ArtifactTaskType.SITE] = 1
        reasons_map[ArtifactTaskType.SITE].append("fallback default to site")

    ranked = sorted(
        [
            MissionArtifactCandidate(
                task_type=task_type,
                score=score,
                reasons=reasons_map.get(task_type, []),
            )
            for task_type, score in scores.items()
        ],
        key=lambda item: item.score,
        reverse=True,
    )
    return ranked


def _derive_name(request: MissionArtifactRequest, selected: ArtifactTaskType) -> str:
    constraints = request.constraints or {}
    payload = request.payload or {}

    preferred_name = (
        constraints.get("name")
        or payload.get("name")
        or payload.get("title")
        or constraints.get("title")
    )
    if preferred_name:
        return str(preferred_name)[:120]

    objective = (request.objective or "").strip()
    cleaned = re.sub(r"^(create|build|make|prepare|generate)\s+", "", objective, flags=re.IGNORECASE)
    cleaned = cleaned.strip(" .,-")
    if cleaned:
        return cleaned[:120]

    fallback_map = {
        ArtifactTaskType.SITE: "Generated Site",
        ArtifactTaskType.TABLE: "Generated Table",
        ArtifactTaskType.GAME: "Generated Game",
        ArtifactTaskType.YOUTUBE_PACK: "Generated YouTube Pack",
    }
    return fallback_map[selected]


def _build_default_payload(request: MissionArtifactRequest, selected: ArtifactTaskType, artifact_name: str) -> dict:
    payload = dict(request.payload or {})
    constraints = request.constraints or {}

    if selected == ArtifactTaskType.SITE:
        payload.setdefault("title", constraints.get("title") or artifact_name)
        payload.setdefault("hero", constraints.get("hero") or artifact_name)
        payload.setdefault("subtitle", constraints.get("subtitle") or "Generated by Jarvis mission artifact flow.")
        payload.setdefault("cta", constraints.get("cta") or "Get Started")

    elif selected == ArtifactTaskType.TABLE:
        payload.setdefault(
            "rows",
            [
                {"day": 1, "title": "Intro post", "format": "short", "status": "planned"},
                {"day": 2, "title": "Pain point", "format": "short", "status": "planned"},
                {"day": 3, "title": "Tool spotlight", "format": "short", "status": "planned"},
            ],
        )

    elif selected == ArtifactTaskType.GAME:
        payload.setdefault("title", constraints.get("title") or artifact_name)

    elif selected == ArtifactTaskType.YOUTUBE_PACK:
        payload.setdefault("niche", constraints.get("niche") or "AI productivity")
        payload.setdefault("audience", constraints.get("audience") or "beginners and creators")
        payload.setdefault("tone", constraints.get("tone") or "practical and motivating")

    return payload


def build_plan(request: MissionArtifactRequest) -> MissionArtifactPlan:
    candidates = classify_objective(request)
    selected = candidates[0].task_type
    artifact_name = _derive_name(request, selected)
    payload = _build_default_payload(request, selected, artifact_name)

    reasoning: list[str] = []
    if request.preferred_task_type:
        reasoning.append("used preferred task type override")
    else:
        reasoning.append(f"selected top candidate '{selected.value}' with score {candidates[0].score}")
        for reason in candidates[0].reasons:
            reasoning.append(reason)

    return MissionArtifactPlan(
        selected_task_type=selected,
        artifact_name=artifact_name,
        description=request.objective,
        payload=payload,
        candidates=candidates,
        objective=request.objective,
        reasoning=reasoning,
    )
