param(
    [string]$BaseUrl = "http://127.0.0.1:8015"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=== CANVAS BUILDER HEALTH ===" -ForegroundColor Cyan
Invoke-RestMethod -Method GET -Uri "$BaseUrl/api/supervisor/canvas/health" -TimeoutSec 10 | ConvertTo-Json -Depth 20

Write-Host ""
Write-Host "=== CANVAS BUILDER BUILD ===" -ForegroundColor Cyan
$Body = @{
    workflow_name = "jarvis_editable_pipeline_demo"
    webhook_path = "jarvis/generated_pipeline_demo"
    description = "Editable scaffold generated by Jarvis for n8n canvas"
    steps = @(
        @{
            step_id = "step-1"
            action = "echo.step1"
            intent = "editable_demo_step1"
            payload = @{
                message = "editable step 1"
                order = 1
            }
        },
        @{
            step_id = "step-2"
            action = "echo.step2"
            intent = "editable_demo_step2"
            payload = @{
                message = "editable step 2"
                order = 2
            }
        },
        @{
            step_id = "step-3"
            action = "echo.step3"
            intent = "editable_demo_step3"
            payload = @{
                message = "editable step 3"
                order = 3
            }
        }
    )
} | ConvertTo-Json -Depth 20

Invoke-RestMethod `
    -Method POST `
    -Uri "$BaseUrl/api/supervisor/canvas/build" `
    -ContentType "application/json" `
    -Body $Body | ConvertTo-Json -Depth 20