param(
    [string]$BaseUrl = "http://127.0.0.1:8015"
)

$ErrorActionPreference = "Stop"

Write-Host "== Mission graph health =="
Invoke-RestMethod -Method GET -Uri "$BaseUrl/api/mission-graph/health" | ConvertTo-Json -Depth 20

Write-Host "`n== Submit auto-execute YouTube launch graph =="
$body1 = @{
    objective = "Launch a YouTube channel with a landing page and content calendar"
    graph_kind = "youtube_launch"
    auto_execute = $true
    constraints = @{
        name = "AI Launch Pack"
        niche = "AI automation"
        audience = "builders and creators"
        tone = "practical and motivating"
        table_name = "AI Launch Calendar"
        title = "AI Launch Landing"
        hero = "Build your AI launch system"
        subtitle = "Generated by the mission graph"
        cta = "Launch Now"
    }
} | ConvertTo-Json -Depth 20

$graph1 = Invoke-RestMethod -Method POST -Uri "$BaseUrl/api/mission-graph/submit" -ContentType "application/json" -Body $body1
$graph1 | ConvertTo-Json -Depth 100

Write-Host "`n== Read executed graph mission =="
Invoke-RestMethod -Method GET -Uri "$BaseUrl/api/mission-graph/missions/$($graph1.graph_mission_id)" | ConvertTo-Json -Depth 100

Write-Host "`n== Submit planned site+game graph =="
$body2 = @{
    objective = "Build a site and a browser game bundle"
    graph_kind = "site_game_bundle"
    auto_execute = $false
    constraints = @{
        title = "Bundle Landing"
        hero = "Site first, game second"
        subtitle = "Dependency-aware mission graph"
        cta = "Open Bundle"
    }
} | ConvertTo-Json -Depth 20

$graph2 = Invoke-RestMethod -Method POST -Uri "$BaseUrl/api/mission-graph/submit" -ContentType "application/json" -Body $body2
$graph2 | ConvertTo-Json -Depth 100

Write-Host "`n== Execute planned site+game graph =="
Invoke-RestMethod -Method POST -Uri "$BaseUrl/api/mission-graph/missions/$($graph2.graph_mission_id)/execute" | ConvertTo-Json -Depth 100

Write-Host "`n== Latest graph runs =="
Invoke-RestMethod -Method GET -Uri "$BaseUrl/api/mission-graph/runs" | ConvertTo-Json -Depth 100

Write-Host "`nMission graph smoke completed successfully."
