import argparse
import json
from datetime import datetime
from pathlib import Path


def now():
    return datetime.now().isoformat(timespec="seconds")


def read_json(path, default):
    try:
        p = Path(path)
        if not p.exists():
            return default
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return default


def write_json(path, data):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def task_exists(queue, task_id):
    return any(x.get("id") == task_id for x in queue.get("items", []))


def make_gateway_task(task_id, title, priority, lane, plan, details):
    return {
        "id": task_id,
        "title": title,
        "details": details,
        "priority": priority,
        "risk": "low",
        "lane": lane,
        "status": "pending",
        "created_at": now(),
        "evidence_required": True,
        "executor": "gateway_plan_v7_2",
        "gateway_plan": plan,
        "completion_gate": [
            "gateway_steps_executed",
            "evidence_artifact_written",
            "no_failed_required_steps"
        ]
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-root", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--max-new", type=int, default=8)
    args = ap.parse_args()

    root = Path(args.project_root)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    queue_path = root / "state" / "jarvis_brain" / "action_queue_v6_4.json"
    evidence_path = root / "jarvis_stage3_artifacts" / "real_action_evidence" / "latest_real_action_evidence_report.json"
    gateway_path = root / "jarvis_stage3_artifacts" / "unified_tool_gateway_v7_0" / "latest_gateway_smoke.json"

    queue = read_json(queue_path, {"schema": "jarvis.action_queue.v6_4", "items": []})
    evidence = read_json(evidence_path, {})
    gateway = read_json(gateway_path, {})

    verdict = evidence.get("truth_guard", {}).get("verdict")
    backend_status = evidence.get("backend", {}).get("summary", {}).get("status")
    n8n_open = evidence.get("n8n", {}).get("port", {}).get("open")
    gateway_ok = gateway.get("smoke_passed") == gateway.get("smoke_total") and gateway.get("smoke_total", 0) > 0

    date_tag = datetime.now().strftime("%Y%m%d")
    candidates = []

    if verdict == "passed_with_evidence" and gateway_ok:
        candidates.extend([
            make_gateway_task(
                f"auto_health_matrix_{date_tag}",
                "Auto health matrix snapshot",
                10,
                "diagnostics",
                [
                    {"tool": "health_matrix", "args": {"base_url": "http://127.0.0.1:8015"}},
                    {"tool": "latency_probe", "args": {"url": "http://127.0.0.1:8015/health"}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/health_matrix_{date_tag}.md",
                        "title": "Auto Health Matrix",
                        "body": "Generated by V7.2 Auto Task Generator."
                    }}
                ],
                "Create a fresh backend health and latency evidence snapshot."
            ),
            make_gateway_task(
                f"auto_route_inventory_{date_tag}",
                "Auto FastAPI route inventory",
                20,
                "backend",
                [
                    {"tool": "route_scan", "args": {"path": "app"}},
                    {"tool": "openapi_probe", "args": {"base_url": "http://127.0.0.1:8015"}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/route_inventory_{date_tag}.md",
                        "title": "Auto Route Inventory",
                        "body": "Route inventory and OpenAPI probe were requested."
                    }}
                ],
                "Inspect backend routes and OpenAPI availability."
            ),
            make_gateway_task(
                f"auto_error_scan_{date_tag}",
                "Auto artifact error scan",
                30,
                "observability",
                [
                    {"tool": "error_scan", "args": {"path": "jarvis_stage3_artifacts"}},
                    {"tool": "latest_artifacts", "args": {"path": "jarvis_stage3_artifacts", "limit": 50}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/error_scan_{date_tag}.md",
                        "title": "Auto Error Scan",
                        "body": "Scanned recent artifacts for error/exception/failure patterns."
                    }}
                ],
                "Search artifacts for error, exception, traceback and failed markers."
            ),
            make_gateway_task(
                f"auto_code_metrics_{date_tag}",
                "Auto code metrics snapshot",
                40,
                "code_quality",
                [
                    {"tool": "code_metrics", "args": {"path": "app"}},
                    {"tool": "python_syntax_scan", "args": {"path": "app", "limit": 200}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/code_metrics_{date_tag}.md",
                        "title": "Auto Code Metrics",
                        "body": "Code metrics and Python syntax scan were requested."
                    }}
                ],
                "Collect basic code metrics and syntax status."
            ),
            make_gateway_task(
                f"auto_memory_index_{date_tag}",
                "Auto memory index snapshot",
                50,
                "memory",
                [
                    {"tool": "memory_index", "args": {}},
                    {"tool": "memory_write_summary", "args": {
                        "title": "Auto Memory Index Snapshot",
                        "body": "V7.2 generated memory index snapshot."
                    }}
                ],
                "Index memory artifacts and write a new summary."
            ),
            make_gateway_task(
                f"auto_queue_summary_{date_tag}",
                "Auto queue summary snapshot",
                60,
                "queue",
                [
                    {"tool": "queue_summary", "args": {}},
                    {"tool": "queue_ready", "args": {"limit": 20}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/queue_summary_{date_tag}.md",
                        "title": "Auto Queue Summary",
                        "body": "Queue summary and ready-task scan were requested."
                    }}
                ],
                "Create queue state snapshot."
            ),
            make_gateway_task(
                f"auto_secret_scan_{date_tag}",
                "Auto safe secret leak scan",
                70,
                "safety",
                [
                    {"tool": "secret_leak_scan", "args": {"path": "app"}},
                    {"tool": "config_inventory", "args": {}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/secret_scan_{date_tag}.md",
                        "title": "Auto Secret Leak Scan",
                        "body": "Safe scan for potential secret-like patterns and config inventory."
                    }}
                ],
                "Scan code/config inventory for possible exposed secrets without printing secret values."
            ),
            make_gateway_task(
                f"auto_state_backup_{date_tag}",
                "Auto state backup",
                80,
                "recovery",
                [
                    {"tool": "backup_state", "args": {}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/state_backup_{date_tag}.md",
                        "title": "Auto State Backup",
                        "body": "State backup requested by V7.2 Auto Task Generator."
                    }}
                ],
                "Create safe backup of state directory."
            )
        ])

        if n8n_open:
            candidates.append(
                make_gateway_task(
                    f"auto_n8n_probe_{date_tag}",
                    "Auto n8n health probe",
                    35,
                    "n8n",
                    [
                        {"tool": "n8n_health_matrix", "args": {"base_url": "http://127.0.0.1:5678"}},
                        {"tool": "n8n_workflow_stub", "args": {
                            "name": f"Jarvis Auto Stub {date_tag}",
                            "path": f"jarvis_stage3_artifacts/n8n_workflows_v7_2/auto_stub_{date_tag}.json"
                        }},
                        {"tool": "md_report", "args": {
                            "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/n8n_probe_{date_tag}.md",
                            "title": "Auto n8n Probe",
                            "body": "n8n health and workflow stub generation requested."
                        }}
                    ],
                    "Probe n8n and generate a workflow stub artifact."
                )
            )

    if backend_status == "partial":
        candidates.append(
            make_gateway_task(
                f"auto_backend_partial_review_{date_tag}",
                "Auto backend partial-health review",
                15,
                "diagnostics",
                [
                    {"tool": "health_matrix", "args": {"base_url": "http://127.0.0.1:8015"}},
                    {"tool": "error_scan", "args": {"path": "jarvis_stage3_artifacts/backend_logs"}},
                    {"tool": "restart_backend_plan", "args": {}},
                    {"tool": "md_report", "args": {
                        "path": f"jarvis_stage3_artifacts/auto_reports_v7_2/backend_partial_review_{date_tag}.md",
                        "title": "Backend Partial Health Review",
                        "body": "Backend was partial, so V7.2 generated a safe diagnostic task and restart plan only."
                    }}
                ],
                "Backend is partial, so create safe diagnostics and a restart plan without restarting automatically."
            )
        )

    added = []
    for task in candidates:
        if len(added) >= args.max_new:
            break
        if not task_exists(queue, task["id"]):
            queue.setdefault("items", []).append(task)
            added.append(task["id"])

    queue["updated_at"] = now()
    write_json(queue_path, queue)

    report = {
        "schema": "jarvis.auto_task_generator.v7_2",
        "created_at": now(),
        "truth_guard_verdict": verdict,
        "backend_status": backend_status,
        "n8n_open": n8n_open,
        "gateway_ok": gateway_ok,
        "candidates": len(candidates),
        "added": added,
        "queue_size": len(queue.get("items", [])),
        "queue_path": str(queue_path)
    }

    write_json(out / "latest_auto_task_generator_report.json", report)

    md = [
        "# Jarvis Auto Task Generator V7.2",
        "",
        f"Created: `{report['created_at']}`",
        f"Truth Guard: `{verdict}`",
        f"Backend status: `{backend_status}`",
        f"n8n open: `{n8n_open}`",
        f"Gateway OK: `{gateway_ok}`",
        f"Candidates: `{len(candidates)}`",
        f"Added: `{len(added)}`",
        "",
        "## Added tasks"
    ]
    if added:
        for x in added:
            md.append(f"- ✅ `{x}`")
    else:
        md.append("- No new tasks added.")

    (out / "latest_auto_task_generator_report.md").write_text("\n".join(md) + "\n", encoding="utf-8")

    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())