from __future__ import annotations
import argparse
import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS_DIR = ROOT / "jarvis_stage3_artifacts"
LOGS_DIR = ARTIFACTS_DIR / "logs"
REPORTS_DIR = ARTIFACTS_DIR / "reports"

ALLOWED_COMMANDS = {
    "python --version",
    "python -V",
    "git status",
    "git branch",
}

@dataclass
class ToolResult:
    ok: bool
    action: str
    message: str
    data: dict

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, indent=2)

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def ensure_dirs() -> None:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False, dir=str(path.parent)) as tmp:
        tmp.write(content)
        temp_name = tmp.name
    os.replace(temp_name, path)

def safe_resolve(user_path: str) -> Path:
    p = (ROOT / user_path).resolve()
    if ROOT not in p.parents and p != ROOT:
        raise ValueError(f"Path escapes project root: {user_path}")
    return p

def log_result(action: str, result: ToolResult) -> None:
    ensure_dirs()
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = LOGS_DIR / f"{stamp}_{action}.json"
    atomic_write_text(path, result.to_json())

class JarvisRealTools:
    def file_write(self, relative_path: str, content: str) -> ToolResult:
        try:
            target = safe_resolve(relative_path)
            atomic_write_text(target, content)
            result = ToolResult(True, "file_write", "File written successfully", {
                "path": str(target),
                "bytes_written": len(content.encode("utf-8")),
                "timestamp": now_iso(),
            })
        except Exception as exc:
            result = ToolResult(False, "file_write", f"Failed to write file: {exc}", {"timestamp": now_iso()})
        log_result("file_write", result)
        return result

    def file_read(self, relative_path: str) -> ToolResult:
        try:
            target = safe_resolve(relative_path)
            content = target.read_text(encoding="utf-8", errors="replace")
            result = ToolResult(True, "file_read", "File read successfully", {
                "path": str(target),
                "content": content[:20000],
                "timestamp": now_iso(),
            })
        except Exception as exc:
            result = ToolResult(False, "file_read", f"Failed to read file: {exc}", {"timestamp": now_iso()})
        log_result("file_read", result)
        return result

    def scaffold_fastapi(self, name: str) -> ToolResult:
        try:
            safe_name = re.sub(r"[^a-zA-Z0-9_-]", "_", name).strip("_")
            if not safe_name:
                raise ValueError("Invalid project name")

            project_dir = safe_resolve(f"jarvis_stage3_artifacts/generated_projects/{safe_name}")
            app_dir = project_dir / "app"
            tests_dir = project_dir / "tests"

            files = {
                project_dir / "requirements.txt": "fastapi>=0.115.0\nuvicorn[standard]>=0.30.0\npytest>=8.0.0\nhttpx>=0.27.0\n",
                project_dir / ".gitignore": ".venv/\n__pycache__/\n.pytest_cache/\n*.pyc\n*.pyo\n*.pyd\n.env\ncoverage/\nhtmlcov/\n",
                project_dir / "pytest.ini": "[pytest]\ntestpaths = tests\npython_files = test_*.py\naddopts = -q\n",
                project_dir / "README.md": f"# {safe_name}\n\nGenerated by Jarvis.\n\n## Run\n\n```powershell\npython -m venv .venv\n.\\.venv\\Scripts\\Activate.ps1\npip install -r requirements.txt\nuvicorn app.main:app --host 127.0.0.1 --port 8000\n```\n\n## Test\n\n```powershell\npytest\n```\n",
                project_dir / "run_api.ps1": "$ErrorActionPreference = 'Stop'\nSet-Location -LiteralPath $PSScriptRoot\nif (Test-Path .\\.venv\\Scripts\\Activate.ps1) { . .\\.venv\\Scripts\\Activate.ps1 }\npython -m uvicorn app.main:app --host 127.0.0.1 --port 8000\n",
                project_dir / "run_tests.ps1": "$ErrorActionPreference = 'Stop'\nSet-Location -LiteralPath $PSScriptRoot\nif (Test-Path .\\.venv\\Scripts\\Activate.ps1) { . .\\.venv\\Scripts\\Activate.ps1 }\npython -m pytest\n",
                app_dir / "__init__.py": "",
                app_dir / "main.py": "from fastapi import FastAPI\n\napp = FastAPI(title='Jarvis Generated API')\n\n@app.get('/health')\ndef health():\n    return {'status': 'healthy', 'service': 'generated_fastapi_project'}\n",
                tests_dir / "test_health.py": "import sys\nfrom pathlib import Path\n\nROOT = Path(__file__).resolve().parents[1]\nif str(ROOT) not in sys.path:\n    sys.path.insert(0, str(ROOT))\n\nfrom fastapi.testclient import TestClient\nfrom app.main import app\n\nclient = TestClient(app)\n\ndef test_health():\n    response = client.get('/health')\n    assert response.status_code == 200\n    body = response.json()\n    assert body['status'] == 'healthy'\n    assert 'service' in body\n",
            }

            for path, content in files.items():
                atomic_write_text(path, content)

            result = ToolResult(True, "scaffold_fastapi", "FastAPI project scaffold created successfully", {
                "project_name": safe_name,
                "project_path": str(project_dir),
                "timestamp": now_iso(),
            })
        except Exception as exc:
            result = ToolResult(False, "scaffold_fastapi", f"Failed to scaffold project: {exc}", {"timestamp": now_iso()})
        log_result("scaffold_fastapi", result)
        return result

    def safe_shell(self, command_text: str, timeout: int = 30) -> ToolResult:
        try:
            command_text = command_text.strip()
            if command_text not in ALLOWED_COMMANDS:
                raise PermissionError("Command is not allowed")
            completed = subprocess.run(
                command_text,
                cwd=str(ROOT),
                shell=True,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
            )
            result = ToolResult(completed.returncode == 0, "safe_shell", "Shell command executed", {
                "command": command_text,
                "returncode": completed.returncode,
                "stdout": completed.stdout[-12000:],
                "stderr": completed.stderr[-12000:],
                "timestamp": now_iso(),
            })
        except Exception as exc:
            result = ToolResult(False, "safe_shell", f"Failed to execute command: {exc}", {"timestamp": now_iso()})
        log_result("safe_shell", result)
        return result

    def smoke_test(self) -> ToolResult:
        try:
            w = self.file_write("jarvis_stage3_artifacts/smoke/smoke_test.txt", "Jarvis smoke test OK")
            if not w.ok:
                raise RuntimeError(w.message)
            r = self.file_read("jarvis_stage3_artifacts/smoke/smoke_test.txt")
            if not r.ok:
                raise RuntimeError(r.message)
            s = self.safe_shell("python --version", 20)
            result = ToolResult(w.ok and r.ok and s.ok, "smoke_test", "Smoke test finished", {
                "write": w.data,
                "read": r.data,
                "shell": s.data,
                "timestamp": now_iso(),
            })
        except Exception as exc:
            result = ToolResult(False, "smoke_test", f"Smoke test failed: {exc}", {"timestamp": now_iso()})
        log_result("smoke_test", result)
        return result

def main() -> int:
    ensure_dirs()
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    p1 = sub.add_parser("file-write")
    p1.add_argument("--path", required=True)
    p1.add_argument("--content", required=True)

    p2 = sub.add_parser("file-read")
    p2.add_argument("--path", required=True)

    p3 = sub.add_parser("scaffold-fastapi")
    p3.add_argument("--name", required=True)

    p4 = sub.add_parser("safe-shell")
    p4.add_argument("--command-text", dest="command_text", required=True)
    p4.add_argument("--timeout", type=int, default=30)

    sub.add_parser("smoke")

    args = parser.parse_args()
    tools = JarvisRealTools()

    if args.cmd == "file-write":
        result = tools.file_write(args.path, args.content)
    elif args.cmd == "file-read":
        result = tools.file_read(args.path)
    elif args.cmd == "scaffold-fastapi":
        result = tools.scaffold_fastapi(args.name)
    elif args.cmd == "safe-shell":
        result = tools.safe_shell(args.command_text, args.timeout)
    elif args.cmd == "smoke":
        result = tools.smoke_test()
    else:
        result = ToolResult(False, "unknown", "Unknown command", {})

    print(result.to_json())
    return 0 if result.ok else 1

if __name__ == "__main__":
    raise SystemExit(main())


